<?php
/*********************************************************************************************************
 This code is part of the ShoutBox software (www.gerd-tentler.de/tools/shoutbox), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

//========================================================================================================
// Smilies (code => image name)
//========================================================================================================

  $sm[':D'] = $sm[':oD'] = $sm[':-D'] = $sm[':))'] = $sm[':o))'] = $sm[':-))'] = 'biggrin.gif';
  $sm[':)'] = $sm[':o)'] = $sm[':-)'] = 'smile.gif';
  $sm[';)'] = $sm[';o)'] = $sm[';-)'] = 'wink.gif';
  $sm[':|'] = $sm[':o|'] = $sm[':-|'] = 'neutral.gif';
  $sm[':/'] = $sm[':o/'] = $sm[':-/'] = 'unsure.gif';
  $sm[':['] = $sm[':o['] = $sm[':-['] = $sm[':('] = $sm[':o('] = $sm[':-('] = 'sad.gif';
  $sm[':P'] = $sm[':oP'] = $sm[':-P'] = 'tongue.gif';
  $sm[':o'] = $sm[':oO'] = $sm[':-o'] = 'surprised.gif';
  $sm[':x'] = $sm[':ox'] = $sm[':-x'] = 'angry.gif';
  $sm['->'] = $sm['=>'] = $sm['-&gt;'] = $sm['=&gt;'] = 'arrow.gif';

  $sm[':blush:'] = 'blush.gif';
  $sm[':confused:'] = 'confused.gif';
  $sm[':cool:'] = 'cool.gif';
  $sm[':cry:'] = 'cry.gif';
  $sm[':eek:'] = 'eek.gif';
  $sm[':evil:'] = 'evil.gif';
  $sm[':exclaim:'] = 'exclaim.gif';
  $sm[':glad:'] = 'glad.gif';
  $sm[':idea:'] = 'idea.gif';
  $sm[':lol:'] = 'lol.gif';
  $sm[':naughty:'] = 'naughty.gif';
  $sm[':question:'] = 'question.gif';
  $sm[':roll:'] = 'rollseyes.gif';
  $sm[':smirk:'] = 'smirk.gif';
  $sm[':tired:'] = 'tired.gif';
  $sm[':zonked:'] = 'zonked.gif';
?>
