--- a/Makefile	2016-04-13 01:07:09.000000000 +0000
+++ b/Makefile	2016-04-29 03:07:38.042692543 +0000
@@ -127,10 +127,10 @@
 		$(OPKG) update || true; \
 	fi
 	$(MAKE) package_install
+	$(MAKE) package_postinst
 ifneq ($(USER_FILES),)
 	$(MAKE) copy_files
 endif
-	$(MAKE) package_postinst
 	$(MAKE) build_image
 
 package_index: FORCE
